# Generated by Django 5.2 on 2025-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
